apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hcm-ai-argocd-permissions-patch
  namespace: maas-config
spec:
  destination:
    name: in-cluster
  project: default
  source:
    path: patch/argocd-permissions
    repoURL: 'https://github.com/app-sre/hcm-ai-playground'
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      allowEmpty: false
    prune: false
