apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rhel-lightspeed-ai

resources:
  - pvc.yaml
  - pvc-config.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

commonLabels:
  app: rhelaiis
  managed-by: argocd